name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  AQUA_USER: ${{ secrets.AQUA_USER }} # Aqua Registry
  AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }} # Aqua Registry
  AQUA_TOKEN: ${{ secrets.AQUA_TOKEN }} # Aqua Scanner authentication
  AQUA_HOST: ${{ secrets.AQUA_HOST }} # Aqua Scanner authentication
  DOCKER_USER: ${{ secrets.DOCKER_USER }} # Docker Registry 
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} # Docker Registry 
  BUILD_NUMBER: ${{ github.run_id }}
  BUILD_NAME: ${{ github.repository }}
  GITHUB_WORKSPACE: ${{ github.workspace }}
  IMAGE_NAME: stanhoe/spring4shell:githubpush
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME
        docker image ls
      
    - name: Aqua Image Scanner
      run: |
        docker image ls
        docker login registry.aquasec.com -u $AQUA_USER -p $AQUA_PASSWORD
        docker pull registry.aquasec.com/scanner:2022.4
        docker run --rm -v $GITHUB_WORKSPACE:/tmp -v /var/run/docker.sock:/var/run/docker.sock -e BUILD_NUMBER=$BUILD_NUMBER -e BUILD_JOB_NAME=$BUILD_NAME registry.aquasec.com/scanner:2022.4 scan -w /tmp --host $AQUA_HOST --token $AQUA_TOKEN --show-negligible --local $IMAGE_NAME --htmlfile /tmp/out.html --jsonfile /tmp/out.json > /dev/null
   
    - name: Push to docker registry
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD    
        docker push $IMAGE_NAME
    
    - uses: actions/upload-artifact@v3
      with:
        name: aqua-artifact
        path: out.*

